// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package project

import (
	"github.com/google/wire"
	"github.com/philipf/gt/internal/toggl"
	"github.com/philipf/gt/internal/toggl/http"
)

// Injectors from inject_defaults.go:

func initialiseProjectService() toggl.ProjectService {
	togglProjectGateway := provideTogglProjectGateway()
	togglProjectService := toggl.NewProjectService(togglProjectGateway)
	return togglProjectService
}

// inject_defaults.go:

func provideTogglProjectGateway() *http.TogglProjectGateway {
	g := new(http.TogglProjectGateway)
	return g
}

var set = wire.NewSet(
	provideTogglProjectGateway, wire.Bind(new(toggl.ProjectGateway), new(*http.TogglProjectGateway)), toggl.NewProjectService,
)
