// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"github.com/google/wire"
	"github.com/philipf/gt/internal/toggl"
	"github.com/philipf/gt/internal/toggl/http"
)

// Injectors from inject_defaults.go:

func initializeClientService() toggl.ClientService {
	togglClientGateway := provideToggleClientGateway()
	togglClientService := toggl.NewClientService(togglClientGateway)
	return togglClientService
}

// inject_defaults.go:

func provideToggleClientGateway() *http.TogglClientGateway {
	g := new(http.TogglClientGateway)
	return g
}

var set = wire.NewSet(
	provideToggleClientGateway, wire.Bind(new(toggl.ClientGateway), new(*http.TogglClientGateway)), toggl.NewClientService,
)
